module.exports = [
  {
    name: 'AWS Lambda',
    provider: 'AWS',
    category: 'Compute',
    link: '/stack/aws-lambda/',
  },
  {
    name: 'Amazon DynamoDB',
    provider: 'AWS',
    category: 'Database',
    link: '/stack/dynamodb/',
  },
  {
    name: 'Identity',
    provider: 'Other',
    category: 'Auth',
    link: 'https://www.netlify.com/docs/identity/',
  },
  {
    name: 'Auth0',
    provider: 'Other',
    category: 'Auth',
    link: 'https://auth0.com/',
  },
  {
    name: 'Amazon Cognito',
    provider: 'AWS',
    category: 'Auth',
    link: 'https://aws.amazon.com/cognito/',
  },
  {
    name: 'FaunaDB',
    provider: 'Other',
    category: 'Database',
    link: 'https://fauna.com/',
  },
  {
    name: 'AWS Fargate',
    provider: 'AWS',
    category: 'Compute',
    link: 'https://aws.amazon.com/fargate/',
  },
  {
    name: 'Amazon S3',
    provider: 'AWS',
    category: 'Storage',
    link: 'https://aws.amazon.com/s3/',
  },
  {
    name: 'Amazon EFS',
    provider: 'AWS',
    category: 'Storage',
    link: 'https://aws.amazon.com/efs/',
  },
  {
    name: 'Amazon Aurora',
    provider: 'AWS',
    category: 'Database',
    link: 'https://aws.amazon.com/rds/aurora/serverless/',
  },
  {
    name: 'Amazon API Gateway',
    provider: 'AWS',
    category: 'API',
    link: 'https://aws.amazon.com/api-gateway/',
  },
  {
    name: 'Amazon SNS',
    provider: 'AWS',
    category: 'Integration',
    link: 'https://aws.amazon.com/sns/',
  },
  {
    name: 'AWS Appsync',
    provider: 'AWS',
    category: 'API',
    link: '/stack/appsync/',
  },
  {
    name: 'Amazon SQS',
    provider: 'AWS',
    category: 'Integration',
    link: 'https://aws.amazon.com/sqs/',
  },
  {
    name: 'Amazon EventBridge',
    provider: 'AWS',
    category: 'Integration',
    link: 'https://aws.amazon.com/eventbridge/',
  },
  {
    name: 'AWS Step Functions',
    provider: 'AWS',
    category: 'Integration',
    link: '/stack/step-functions/',
  },
  {
    name: 'Amazon Kinesis',
    provider: 'AWS',
    category: 'Analytics',
    link: 'https://aws.amazon.com/kinesis/',
  },
  {
    name: 'Amazon Athena',
    provider: 'AWS',
    category: 'Analytics',
    link: 'https://aws.amazon.com/athena/',
  },
  {
    name: 'Cloud Firestore',
    provider: 'Google Cloud',
    category: 'Database',
    link: 'https://cloud.google.com/firestore/',
  },
  {
    name: 'Firebase Realtime Database',
    provider: 'Google Cloud',
    category: 'Database',
    link: 'https://firebase.google.com/products/realtime-database/',
  },
  {
    name: 'Google Cloud Functions',
    provider: 'Google Cloud',
    category: 'Compute',
    link: 'https://cloud.google.com/functions/',
  },
  {
    name: 'BigQuery',
    provider: 'Google Cloud',
    category: 'Analytics',
    link: 'https://cloud.google.com/bigquery/',
  },
  {
    name: 'Cloud Dataflow',
    provider: 'Google Cloud',
    category: 'Integration',
    link: 'https://cloud.google.com/dataflow/',
  },
  {
    name: 'Algolia',
    provider: 'Other',
    category: 'Other',
    otherFallbackCategory: 'Search',
    link: 'https://www.algolia.com/',
  },
  {
    name: 'Azure Functions',
    provider: 'Azure',
    category: 'Compute',
    link: 'https://azure.microsoft.com/en-us/services/functions/',
  },
  {
    name: 'Braintree',
    provider: 'Other',
    category: 'Other',
    otherFallbackCategory: 'Payments',
    link: 'https://www.braintreepayments.com/',
  },
  {
    name: 'Stripe',
    provider: 'Other',
    category: 'Other',
    otherFallbackCategory: 'Payments',
    link: 'https://stripe.com/',
  },
  {
    name: 'MongoDB Stitch',
    provider: 'Other',
    category: 'Database',
    link: 'https://www.mongodb.com/cloud/stitch',
  },
  {
    name: 'Twilio',
    provider: 'Other',
    category: 'Communication',
    link: 'https://www.twilio.com/',
  },
  {
    name: 'SendGrid',
    provider: 'Other',
    category: 'Communication',
    link: 'https://sendgrid.com/',
  },
  {
    name: 'Amazon SES',
    provider: 'AWS',
    category: 'Communication',
    link: 'https://aws.amazon.com/ses/',
  },
  {
    name: 'Blob Storage',
    provider: 'Azure',
    category: 'Storage',
    link: 'https://azure.microsoft.com/en-us/services/storage/blobs/',
  },
]
