module.exports = [
  {
    name: 'AWS Lambda',
    provider: 'AWS',
    category: 'Compute',
    link: '/aws-lambda/',
    slug: 'stack-aws-lambda',
    highlighted: true,
  },
  {
    name: 'Amazon DynamoDB',
    provider: 'AWS',
    category: 'Database',
    link: '/dynamodb/',
    slug: 'stack-dynamodb',
    highlighted: true,
  },
  {
    name: 'Netlify Identity',
    provider: 'Other',
    category: 'Auth',
    link: 'https://www.netlify.com/docs/identity/',
    slug: 'stack-netlify-identity',
    highlighted: true,
  },
  {
    name: 'Auth0',
    provider: 'Other',
    category: 'Auth',
    link: 'https://auth0.com/',
    slug: 'stack-auth0',
    highlighted: true,
  },
  {
    name: 'Amazon Cognito',
    provider: 'AWS',
    category: 'Auth',
    link: 'https://aws.amazon.com/cognito/',
    slug: 'stack-aws-cognito',
    highlighted: true,
  },
  {
    name: 'FaunaDB',
    provider: 'Other',
    category: 'Database',
    link: 'https://fauna.com/',
    slug: 'stack-faunadb',
    highlighted: true,
  },
  {
    name: 'AWS Fargate',
    provider: 'AWS',
    category: 'Compute',
    link: 'https://aws.amazon.com/fargate/',
    slug: 'stack-aws-fargate',
    highlighted: true,
  },
  {
    name: 'Amazon S3',
    provider: 'AWS',
    category: 'Storage',
    link: 'https://aws.amazon.com/s3/',
    slug: 'stack-s3',
    highlighted: true,
  },
  {
    name: 'Amazon EFS',
    provider: 'AWS',
    category: 'Storage',
    link: 'https://aws.amazon.com/efs/',
    slug: 'stack-amazon-efs',
    highlighted: true,
  },
  {
    name: 'Amazon Aurora',
    provider: 'AWS',
    category: 'Database',
    link: 'https://aws.amazon.com/rds/aurora/serverless/',
    slug: 'stack-amazon-aurora',
    highlighted: true,
  },
  {
    name: 'Amazon API Gateway',
    provider: 'AWS',
    category: 'API',
    link: 'https://aws.amazon.com/api-gateway/',
    slug: 'stack-api-gateway',
    highlighted: true,
  },
  {
    name: 'Amazon SNS',
    provider: 'AWS',
    category: 'Integration',
    link: 'https://aws.amazon.com/sns/',
    slug: 'stack-amazon-sns',
    highlighted: true,
  },
  {
    name: 'AWS Appsync',
    provider: 'AWS',
    category: 'API',
    link: '/aws-appsync/',
    slug: 'stack-aws-appsync',
    highlighted: true,
  },
  {
    name: 'Amazon SQS',
    provider: 'AWS',
    category: 'Integration',
    link: 'https://aws.amazon.com/sqs/',
    slug: 'stack-amazon-sqs',
    highlighted: true,
  },
  {
    name: 'Amazon EventBridge',
    provider: 'AWS',
    category: 'Integration',
    link: 'https://aws.amazon.com/eventbridge/',
    slug: 'stack-eventbridge',
    highlighted: true,
  },
  {
    name: 'AWS Step Functions',
    provider: 'AWS',
    category: 'Integration',
    link: '/step-functions/',
    slug: 'stack-step-functions',
  },
  {
    name: 'Amazon Kinesis',
    provider: 'AWS',
    category: 'Analytics',
    link: 'https://aws.amazon.com/kinesis/',
    slug: 'stack-amazon-kinesis',
  },
  {
    name: 'Amazon Athena',
    provider: 'AWS',
    category: 'Analytics',
    link: 'https://aws.amazon.com/athena/',
    slug: 'stack-amazon-athena',
  },
  {
    name: 'Amazon Rekognition',
    provider: 'AWS',
    category: 'Machine Learning',
    link: 'https://aws.amazon.com/rekognition/',
    slug: 'stack-amazon-rekognition',
  },
  {
    name: 'Cloud Firestore',
    provider: 'Google Cloud',
    category: 'Database',
    link: 'https://cloud.google.com/firestore/',
    slug: 'stack-cloud-firestone',
  },
  {
    name: 'Firebase Realtime Database',
    provider: 'Google Cloud',
    category: 'Database',
    link: 'https://firebase.google.com/products/realtime-database/',
    slug: 'stack-firebase-database',
  },
  {
    name: 'Google Cloud Functions',
    provider: 'Google Cloud',
    category: 'Compute',
    link: 'https://cloud.google.com/functions/',
    slug: 'stack-google-cloud-functions',
  },
  {
    name: 'BigQuery',
    provider: 'Google Cloud',
    category: 'Analytics',
    link: 'https://cloud.google.com/bigquery/',
    slug: 'stack-bigquery',
  },
  {
    name: 'Cloud Dataflow',
    provider: 'Google Cloud',
    category: 'Integration',
    link: 'https://cloud.google.com/dataflow/',
    slug: 'stack-cloud-dataflow',
  },
  {
    name: 'Algolia',
    provider: 'Other',
    category: 'Other',
    otherFallbackCategory: 'Search',
    link: 'https://www.algolia.com/',
    slug: 'stack-algolia',
  },
  {
    name: 'Azure Functions',
    provider: 'Azure',
    category: 'Compute',
    link: 'https://azure.microsoft.com/en-us/services/functions/',
    slug: 'stack-azure-functions',
  },
  {
    name: 'Braintree',
    provider: 'Other',
    category: 'Other',
    otherFallbackCategory: 'Payments',
    link: 'https://www.braintreepayments.com/',
    slug: 'stack-braintree',
  },
  {
    name: 'Stripe',
    provider: 'Other',
    category: 'Other',
    otherFallbackCategory: 'Payments',
    link: 'https://stripe.com/',
    slug: 'stack-stripe',
  },
  {
    name: 'MongoDB Stitch',
    provider: 'Other',
    category: 'Database',
    link: 'https://www.mongodb.com/cloud/stitch',
    slug: 'stack-mongodb-stitch',
  },
  {
    name: 'Twilio',
    provider: 'Other',
    category: 'Communication',
    link: 'https://www.twilio.com/',
    slug: 'stack-twilio',
  },
  {
    name: 'SendGrid',
    provider: 'Other',
    category: 'Communication',
    link: 'https://sendgrid.com/',
    slug: 'stack-sendgrid',
  },
  {
    name: 'Amazon SES',
    provider: 'AWS',
    category: 'Communication',
    link: 'https://aws.amazon.com/ses/',
    slug: 'stack-amazon-ses',
  },
  {
    name: 'Blob Storage',
    provider: 'Azure',
    category: 'Storage',
    link: 'https://azure.microsoft.com/en-us/services/storage/blobs/',
    slug: 'stack-blob-storage',
  },
  {
    name: 'Zeit',
    provider: 'Other',
    category: 'Compute',
    link: 'https://zeit.co/',
    slug: 'stack-zeit',
  },
  {
    name: 'Netlify Functions',
    provider: 'Other',
    category: 'Compute',
    link: 'https://www.netlify.com/docs/functions/',
    slug: 'stack-netlify-functions',
  },
  {
    name: 'Amazon Polly',
    provider: 'AWS',
    category: 'Machine Learning',
    link: 'https://aws.amazon.com/polly/',
    slug: 'stack-amazon-polly',
  },
  {
    name: 'Cloud Text-to-Speech',
    provider: 'Google Cloud',
    category: 'Machine Learning',
    link: 'https://cloud.google.com/text-to-speech/',
    slug: 'stack-cloud-text-to-speech',
  },
  {
    name: 'Cloud Speech-to-Text',
    provider: 'Google Cloud',
    category: 'Machine Learning',
    link: 'https://cloud.google.com/speech-to-text/',
    slug: 'stack-cloud-speech-to-text',
  },
  {
    name: 'Natural Language',
    provider: 'Google Cloud',
    category: 'Machine Learning',
    link: 'https://cloud.google.com/natural-language/',
    slug: 'stack-natural-language',
  },
  {
    name: 'Amazon Comprehend',
    provider: 'AWS',
    category: 'Machine Learning',
    link: 'https://aws.amazon.com/comprehend/',
    slug: 'stack-amazon-comprehend',
  },
  {
    name: 'Amazon Transcribe',
    provider: 'AWS',
    category: 'Machine Learning',
    link: 'https://aws.amazon.com/transcribe/',
    slug: 'stack-amazon-transcribe',
  },
  {
    name: 'Amazon Translate',
    provider: 'AWS',
    category: 'Machine Learning',
    link: 'https://aws.amazon.com/translate/',
    slug: 'stack-amazon-translate',
  },
  {
    name: 'Amazon Textract',
    provider: 'AWS',
    category: 'Machine Learning',
    link: 'https://aws.amazon.com/textract/',
    slug: 'stack-amazon-textract',
  },
  {
    name: 'Amazon Cloudfront',
    provider: 'AWS',
    category: 'Other',
    otherFallbackCategory: 'CDN',
    link: 'https://aws.amazon.com/cloudfront/',
    slug: 'stack-amazon-cloudfront',
  },
  {
    name: 'Amazon Route 53',
    provider: 'AWS',
    category: 'Other',
    otherFallbackCategory: 'DNS',
    link: 'https://aws.amazon.com/route53/',
    slug: 'stack-amazon-route-53',
  },
]
