export default {
  docs: '/framework/docs/',
  why: '/learn/why/',
  what: '/learn/manifesto/',
  cli: '/cli/',
  components: '/components/',
  training: '/training/',
  pricing: '/pricing/',
  about: '/company/overview/',
  support: '/support/',
  learn: '/learn/',
  useCases: '/learn/use-cases/',
  comparisons: '/learn/comparisons/',
  enterprise: '/enterprise/',
  dashboard: 'https://dashboard.serverless.com',
  dashboardPage: '/dashboard/',
  examples: '/examples/',
  plugins: '/plugins/',
  blog: '/blog/',
  caseStudies: '/learn/case-studies/',
  courses: '/courses/',
  github: 'https://github.com/serverless/',
  forum: 'https://forum.serverless.com/',
  slack: '/slack',
  meetups: '/resources/events/',
  partners: '/partners/',
  framework: '/framework/',
  team: '/company/overview/',
  jobs: '/company/jobs/',
  tutorials: '/blog/category/guides-and-tutorials/',
  contact: 'mailto:hello@serverless.com',
  gettingStarted: '/framework/docs/getting-started/',
  contactForm: '/enterprise/contact/',
  providers: '/framework/docs/providers/',
  championsDeck:
    'https://docs.google.com/presentation/d/1LaHodp_UKJd5j8hjNkGUhgHpNaQk-30boF_do4CYOxw/edit?usp=sharing',
  docPages: {
    monitoring: '/framework/docs/dashboard/insights/',
  },
  monitoring: '/monitoring/',
  alerts: '/alerts/',
  policies: '/policies/',
  debugging: '/debugging/',
  integrations: '/integrations/',
  termsOfService: 'https://dashboard.serverless.com/legal/terms',
  privacyPolicy: 'https://dashboard.serverless.com/legal/privacy',
}
