export default {
  platform: {
    //TODO - phaseOut
    framework: '/framework/',
    eventGateway: '/event-gateway/',
    dashboard: '/dashboard/',
  },
  products: {
    framework: '/framework/',
    platform: '/platform/',
    support: '/support/',
  },
  developersMenu: {
    docs: '/framework/docs/',
    plugins: '/plugins/',
    examples: '/examples/',
    quickStarts: '/framework/docs/getting-started/',
    courses: '/courses/',
  },
  community: {
    partners: '/partners/',
    foundries: '',
    forum: 'https://forum.serverless.com/',
    events: '/resources/events/',
    slack: '/slack',
    workshops: '/resources/workshops/',
  },
  developers: {
    documentation: {
      framework: '/framework/docs/',
      platform: 'https://github.com/serverless/platform/tree/master/docs',
      gettingStarted: '/framework/docs/getting-started/',
      examplesAndGuides: '/framework/docs/providers/aws/examples/',
    },
    quickStart: {
      aws: '/framework/docs/providers/aws/guide/quick-start/',
      azure: '/framework/docs/providers/azure/guide/quick-start/',
      google: '/framework/docs/providers/google/guide/quick-start/',
      others: '/framework/docs/',
    },
    examples: {
      docs: '/framework/docs/',
      plugins: '/plugins/',
      examples: '/examples/',
      courses: '/courses/',
    },
  },
  learn: {
    useCases: '/learn/use-cases/',
    why: '/learn/overview/',
    comparisons: '/learn/comparisons/',
    caseStudy: '/learn/case-studies/',
  },
  resources: {
    overview: '/resources/overview/',
    blog: '/blog/',
    forum: 'https://forum.serverless.com/',
    events: '/resources/events/',
    slack: '/slack',
    workshops: '/resources/workshops/',
  },
  company: {
    team: '/company/overview/',
    jobs: '/company/jobs/',
    champions: '/company/champions/',
    contact: 'mailto:hello@serverless.com',
  },
  termsOfService: 'https://dashboard.serverless.com/legal/terms',
  privacyPolicy: 'https://dashboard.serverless.com/legal/privacy',
  facebookHandle: 'https://www.facebook.com/serverless/',
  instagramHandle: 'https://www.instagram.com/serverlessinc/',
  githubHandle: 'https://github.com/serverless/',
  linkedinHandle: 'https://www.linkedin.com/company/serverless/',
  twitterHandle: 'https://twitter.com/goserverless/',
  enterprise: '/enterprise/',
  signup: 'https://dashboard.serverless.com/',
}
