/* Available page templates
 * Usage in markdown ->
 * Layout: Homepage
 */
export { default as PageError } from './404'
export { default as Homepage } from './Homepage'
export { default as PageLoading } from './PageLoading'
export { default as Partners } from './Partners'
export { default as Team } from './Team'
export { default as Community } from './Community'
export { default as Enterprise } from './Enterprise'
export { default as Framework } from './Framework'
export { default as EventGateway } from './EventGateway'
export { default as EventGatewayEntreprise } from './EventGatewayEntreprise'
export { default as EventGatewayBeta } from './EventGatewayBeta'
export { default as Auth } from './Auth'
export { default as Success } from './Success'  // to depricate after 10+ releases
export { default as SuccessNew } from './SuccessNew'
export { default as Splash } from './Splash'
export { default as Jobs } from './Jobs'
export { default as Blog } from './Blog'
export { default as SignUp } from './SignUp'
export { default as Subscribe } from './Subscribe'
export { default as GettingStarted } from './GettingStarted'
export { default as WorkShops } from './WorkShops'
export { default as WorkShopPage } from './WorkShopPage'
export { default as Champions } from './Champions'
export { default as ChampionsAbout } from './Champions/About.js'
export { default as ChampionBiosTH } from './Champions/Bios/TakahiroHorike.js'
export { default as ChampionBiosMV } from './Champions/Bios/MarciaVillalba.js'
export { default as ChampionBiosRSB } from './Champions/Bios/RyanScottBrown.js'
export { default as Blank } from './Blank'
