export default [
  {
    heading: 'Engineering',
    title: 'Senior Software Engineer, Open Source tools',
    location: 'San Franscisco',
    status: 'Full-time',
    link: 'https://jobs.lever.co/serverless/43775278-aaca-4056-9a4a-90124141e30c'
  },
  {
    heading: 'Engineering',
    title: 'Senior/Principal Engineer, Distributed Systems',
    location: 'San Franscisco',
    status: 'Full-time',
    link: 'https://jobs.lever.co/serverless/8386016f-af6d-49e3-b0b6-2ee19a416396',
  },
  {
    heading: 'Engineering',
    title: 'Software Engineer, Distributed Systems (Remote)',
    location: 'Remote',
    status: 'Full-time',
    link: 'https://jobs.lever.co/serverless/7b243d22-cec5-47a9-a047-244e8418497e',
  },
  {
    heading: 'Growth',
    title: 'Customer Success Engineer',
    location: 'San Franscisco',
    status: 'Full-time',
    link: 'https://jobs.lever.co/serverless/dfe8f81b-a526-4e5c-897a-3a662be8ba87',
  },
  {
    heading: 'Growth',
    title: 'Customer Success Engineer (Remote)',
    location: 'Remote',
    status: 'Full-time',
    link: 'https://jobs.lever.co/serverless/dfe8f81b-a526-4e5c-897a-3a662be8ba87',
  },
  {
    heading: 'Growth',
    title: 'Developer Advocate',
    location: 'San Franscisco',
    status: 'Full-time',
    link: 'https://jobs.lever.co/serverless/efa6e178-29eb-4f92-9d28-49fb393421cc',
  },
  {
    heading: 'Growth',
    title: 'Developer Advocate (Remote)',
    location: 'Remote',
    status: 'Full-time',
    link: 'https://jobs.lever.co/serverless/efa6e178-29eb-4f92-9d28-49fb393421cc',
  },
  {
    heading: 'Growth',
    title: 'Growth Engineer',
    location: 'San Franscisco',
    status: 'Full-time',
    link: 'https://jobs.lever.co/serverless/fc98264c-9185-4bb6-a782-8f9955e789e7',
  },
  {
    heading: 'Growth',
    title: 'Growth Engineer (Remote)',
    location: 'Remote',
    status: 'Full-time',
    link: 'https://jobs.lever.co/serverless/fc98264c-9185-4bb6-a782-8f9955e789e7',
  },
  {
    heading: 'Growth',
    title: 'Head of Developer Relations',
    location: 'San Franscisco',
    status: 'Full-time',
    link: 'https://jobs.lever.co/serverless/afc5b2f0-9556-4a8d-978f-63a7b46a762c',
  },
  {
    heading: 'Growth',
    title: 'Head of Developer Relations (Remote)',
    location: 'Remote',
    status: 'Full-time',
    link: 'https://jobs.lever.co/serverless/afc5b2f0-9556-4a8d-978f-63a7b46a762c',
  },
  {
    heading: 'Product',
    title: 'Director/Senior Product Manager, Serverless Platform',
    location: 'San Franscisco',
    status: 'Full-time',
    link: 'https://jobs.lever.co/serverless/df15f449-572f-427c-8ce1-eaf45ecee3d5',
  },
  {
    heading: 'Product',
    title: 'Director/Senior Product Manager, Serverless Platform (Remote)',
    location: 'Remote',
    status: 'Full-time',
    link: 'https://jobs.lever.co/serverless/df15f449-572f-427c-8ce1-eaf45ecee3d5',
  },
  {
    heading: 'Product',
    title: 'Senior Product Manager - Serverless Event Gateway',
    location: 'San Franscisco',
    status: 'Full-time',
    link: 'https://jobs.lever.co/serverless/876cbb6c-83b8-43cc-80d1-4f2e1c1c5b1d',
  },
  {
    heading: 'Product',
    title: 'Senior Product Manager - Serverless Event Gateway (Remote)',
    location: 'Remote',
    status: 'Full-time',
    link: 'https://jobs.lever.co/serverless/876cbb6c-83b8-43cc-80d1-4f2e1c1c5b1d',
  },
  {
    heading: 'Product',
    title: 'Senior UI & UX Designer',
    location: 'San Franscisco',
    status: 'Full-time',
    link: 'https://jobs.lever.co/serverless/4ada61d8-79ff-4336-b3d8-52d9be64aed7',
  },
  {
    heading: 'Product',
    title: 'Senior UI & UX Designer (Remote)',
    location: 'Remote',
    status: 'Full-time',
    link: 'https://jobs.lever.co/serverless/4ada61d8-79ff-4336-b3d8-52d9be64aed7',
  },
]