export { default as HeroDescription } from './HeroDescription'
export { default as HeroInlineDescription } from './HeroInlineDescription'
export { default as HeroMainTitle } from './HeroMainTitle'
export { default as HeroTitle } from './HeroTitle'
export { default as HeroAdvantage } from './HeroAdvantage'